### ISSUE TITLE
Im getting "Null check operator used on a null value" when Im initialising clientViaApplicationDefaultCredentials

### ISSUE THREAD

**Issue by tananga** [google/googleapis.dart#254]
Hi :) 
First please remember that Im relatively new in Dart/Flutter.
Im getting "Caught error: Null check operator used on a null value" after line where  Im initialising "clientViaApplicationDefaultCredentials"
Im trying to get my youtube playlists but I probably making something wrong. Can you please take a look ? Im making exacly how it is in example code. Btw more examples would be great !

`import 'dart:async';
import 'package:googleapis_auth/auth_io.dart';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

import 'package:googleapis/youtube/v3.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/youtube.readonly',
  ],
);

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  GoogleSignInAccount? _currentUser;
  String _contactText = '';

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) {
      setState(() {
        _currentUser = account;
      });
    });
    _googleSignIn.signInSilently();
  }

  void printWrapped(String text) {
    final pattern = RegExp('.{1,800}'); // 800 is the size of each chunk
    pattern.allMatches(text).forEach((match) => print(match.group(0)));
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  Future<void> _handleSignOut() => _googleSignIn.disconnect();

  Widget _buildBody() {
    GoogleSignInAccount? user = _currentUser;
    if (user != null) {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          ListTile(
            title: Text(user.displayName ?? ''),
            subtitle: Text(user.email),
          ),
          const Text("Signed in successfully."),
          Text(_contactText),
          ElevatedButton(
            child: const Text('SIGN OUT'),
            onPressed: _handleSignOut,
          ),
          ElevatedButton(
            child: const Text('REFRESH'),
            onPressed: () => _handleGetPlaylist(user),
          ),
        ],
      );
    } else {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          const Text("You are not currently signed in."),
          ElevatedButton(
            child: const Text('SIGN IN'),
            onPressed: _handleSignIn,
          ),
        ],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }

  _handleGetPlaylist(GoogleSignInAccount? user) async {
    print("_handleGetPlaylist 161719393");
    try {
      print('Awaiting user order...');
      final httpClient = await clientViaApplicationDefaultCredentials(
        scopes: [YouTubeApi.youtubeReadonlyScope],
      );
      print("after clientViaApplicationDefaultCredentials 668601306");
      // final client = http.Client();
      YouTubeApi youtubeApi = YouTubeApi(httpClient);
      print("after youtubeApi 183403194");
      youtubeApi.playlists.list(["part=snippet"], mine: true).then((value) {
        print("OKOK");
        print(value);
      }).catchError((err) {
        print("Problem...");
        print(err);
      });
    } catch (err) {
      print('Caught error: $err');
    }
  }
}
`

OUTPUT:
I/flutter ( 2890): _handleGetPlaylist 161719393
I/flutter ( 2890): Awaiting user order...
I/flutter ( 2890): Caught error: Null check operator used on a null value

**Comment by kevmoo** [comment]
@tananga – would you please include a stack trace? I'd love to know where we're sending the null value.

**Comment by tananga** [comment]
Sure I would love to help. As I said Im new in Dart community so can you please tell me which command should I put in my terminal ? So far Im just typing "flutter run"

**Comment by kevmoo** [comment]
What emulator are you using @tananga ?

**Comment by tananga** [comment]
@kevmoo Im using my phone connected to computer with usb cable.
I typed "flutter run -v" in terminal and after pressing button "refresh" the output is still just:

[  +22 ms] I/flutter ( 4092): _handleGetPlaylist 161719393
[        ] I/flutter ( 4092): Awaiting user order...
[  +23 ms] I/flutter ( 4092): Caught error: Null check operator used on a null value

**Comment by tananga** [comment]
@kevmoo I added a photo

**Comment by kevmoo** [comment]
Ugh! I'm trying to figure out how to get a full stack dump

**Comment by tananga** [comment]
Im gonna record a movie just give me few minutes

**Comment by kevmoo** [comment]
Don't need a movie. Just want a stack trace

**Comment by tananga** [comment]
Ok so how can I do it ?

**Comment by kevmoo** [comment]
> Ok so how can I do it ?

I'm asking around internally!

**Comment by kevmoo** [comment]
@tananga – remove the try/catch block!

or in the catch block, add a use `catch (err, stack) {` and print stack

**Comment by tananga** [comment]
I/flutter (24155): _handleGetPlaylist 161719393
I/flutter (24155): Awaiting user order...
I/flutter (24155): #0      clientViaApplicationDefaultCredentials (package:googleapis_auth/auth_io.dart:70:71)
I/flutter (24155): #1      SignInDemoState._handleGetPlaylist (package:youtube_playlist_saver/main.dart:111:32)
I/flutter (24155): #2      SignInDemoState._buildBody.<anonymous closure> (package:youtube_playlist_saver/main.dart:77:30)
I/flutter (24155): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
I/flutter (24155): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (24155): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
I/flutter (24155): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
I/flutter (24155): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
I/flutter (24155): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
I/flutter (24155): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
I/flutter (24155): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutte
I/flutter (24155): Caught error: Null check operator used on a null value

**Comment by tananga** [comment]
@kevmoo is it ok ?

**Comment by kevmoo** [comment]
> @kevmoo is it ok ?

Absolutely, @tananga 

https://github.com/google/googleapis.dart/blob/072dd0c0c98f8639ade8938d86da9826709c7454/googleapis_auth/lib/auth_io.dart#L71

We should give an error when `HOME` is not defined in environment vars.

**Comment by tananga** [comment]
@kevmoo Sorry for taking your time but can you help me with getting my youtube playlists in my flutter app ? I know how to take my contacts from googles people api but it don't work with youtube. Do you know where can I found some examples about taking private data from youtube ? I know that you probably have much better things to do but its very important for me and I cant find that anywhere.

**Comment by tananga** [comment]
Hey @kevmoo. Are you open to help ? I need to download all users youtube video after he sign-in with google in my flutter app. Is it possible ? I spend few days trying to solve this problem. Can you guys put more examples and code snippets for noobies like me ?

**Comment by kevmoo** [comment]
@tananga – these APIs are generated. And there are a LOT. We're not likely to go too far adding more examples.

Looking through this should help, though: https://developers.google.com/youtube/v3/docs

**Comment by zzterrozz** [comment]
> Hi :) First please remember that Im relatively new in Dart/Flutter. Im getting "Caught error: Null check operator used on a null value" after line where Im initialising "clientViaApplicationDefaultCredentials" Im trying to get my youtube playlists but I probably making something wrong. Can you please take a look ? Im making exacly how it is in example code. Btw more examples would be great !



I am facing a similar error issue when I use firebase to authenticate with GCP Secret Manager in Flutter:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      clientViaApplicationDefaultCredentials (package:googleapis_auth/auth_io.dart:77:49)
````

On Mac I launch in iTerm:
`export GOOGLE_APPLICATION_CREDENTIALS=<PATH_TO_JSON_FILE>`

Then my code is:


```dart

import 'package:googleapis/secretmanager/v1.dart';
import 'package:googleapis_auth/auth_io.dart' as auth;
import 'package:googleapis/firestore/v1.dart';

final client = await auth.clientViaApplicationDefaultCredentials(scopes: [FirestoreApi.cloudPlatformScope]);
final api = SecretManagerApi(client);
final secrets = await api.projects.secrets.versions.access('my_secret_key');
print(secrets.payload!.data.toString());
```
Any idea what is creating this issue?

**Comment by chimura** [comment]
I'm getting the same error when invoking clientViaApplicationDefaultCredentials (Uri.directory(Platform.environment['HOME']!) returning null). I don't have any idea how to set this variable and can't find relevant information anywhere.

**Comment by kevmoo** [comment]
https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth is THE WAY you should do things from a flutter app. I need to update the docs!
