### ISSUE TITLE
Can not handle arrays as response

### ISSUE THREAD

**Issue by torbenkeller** [google/googleapis.dart#295]
The discovery file for the Firestore Api is wrong for the runQuery endpoint as mentioned in #101 so I wanted to fix it for me by changing the `firestore__v1.json` file. 

The response defined in the Discovery Api looks like this:
```json
"response": {
    "$ref": "RunQueryResponse"
},
```

The actual response of the  is a `List` of `RunQueryResponse` so I changed the response to this:
```json
"response": {
    "items": {
        "$ref": "RunQueryResponse"
    },
    "type": "array"
},
```

When generating the code with the change I get the following exception:
```text
stack: #0      DartSchemaForwardRef.resolve (package:discoveryapis_generator/src/dart_schema_types.dart:326:7)
#1      _parseMethod.getValidReference (package:discoveryapis_generator/src/dart_resources.dart:635:42)
#2      _parseMethod (package:discoveryapis_generator/src/dart_resources.dart:691:41)
#3      _parseResource.<anonymous closure> (package:discoveryapis_generator/src/dart_resources.dart:774:26)
#4      orderedForEach (package:discoveryapis_generator/src/utils.dart:31:8)
#5      _parseResource (package:discoveryapis_generator/src/dart_resources.dart:773:5)
#6      _parseResource.<anonymous closure> (package:discoveryapis_generator/src/dart_resources.dart:792:28)
#7      orderedForEach (package:discoveryapis_generator/src/utils.dart:31:8)
#8      _parseResource (package:discoveryapis_generator/src/dart_resources.dart:790:5)
#9      _parseResource.<anonymous closure> (package:discoveryapis_generator/src/dart_resources.dart:792:28)
#10     orderedForEach (package:discoveryapis_generator/src/utils.dart:31:8)
#11     _parseResource (package:discoveryapis_generator/src/dart_resources.dart:790:5)
#12     _parseResource.<anonymous closure> (package:discoveryapis_generator/src/dart_resources.dart:792:28)
#13     orderedForEach (package:discoveryapis_generator/src/utils.dart:31:8)
#14     _parseResource (package:discoveryapis_generator/src/dart_resources.dart:790:5)
#15     parseResources (package:discoveryapis_generator/src/dart_resources.dart:903:10)
#16     new DartApiLibrary.build (package:discoveryapis_generator/src/dart_api_library.dart:90:16)
#17     ApisPackageGenerator._generateApiLibrary (package:discoveryapis_generator/src/apis_package_generator.dart:138:32)
#18     ApisPackageGenerator.generateApiPackage (package:discoveryapis_generator/src/apis_package_generator.dart:111:28)
#19     generateApiPackage (package:discoveryapis_generator/discoveryapis_generator.dart:33:31)
#20     generateAllLibraries (package:discoveryapis_generator/discoveryapis_generator.dart:50:10)
#21     DiscoveryPackagesConfiguration.generate.<anonymous closure> (package:googleapis_generator_dependency/src/package_configuration.dart:166:23)
#22     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#23     DiscoveryPackagesConfiguration.generate (package:googleapis_generator_dependency/src/package_configuration.dart:165:14)
#24     generateFromConfiguration (package:googleapis_generator_dependency/googleapis_generator.dart:212:24)
#25     main (file:///Users/torbenkeller/Yamuntu/googleapis.dart/generator/bin/generate.dart:95:11)
#26     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Seems like the generator can not handle an array response

**Comment by kevmoo** [comment]
Guessing it's just a bug. Pull requests welcome!

**Comment by torbenkeller** [comment]
Seems like I just changed the json the wrong way. It works if the `response` definition stays the same and the `RunQueryResponse` is the `array`.

### Before

```json
"RunQueryResponse": {
    "description": "The response for Firestore.RunQuery.",
    "id": "RunQueryResponse",
    "properties": {
        "document": {
            "$ref": "Document",
            "description": "A query result. Not set when reporting partial progress."
        },
        "readTime": {
            "description": "The time at which the document was read. This may be monotonically increasing; in this case, the previous documents in the result stream are guaranteed not to have changed between their `read_time` and this one. If the query returns no results, a response with `read_time` and no `document` will be sent, and this represents the time at which the query was run.",
            "format": "google-datetime",
            "type": "string"
        },
        "skippedResults": {
            "description": "The number of results that have been skipped due to an offset between the last response and the current response.",
            "format": "int32",
            "type": "integer"
        },
        "transaction": {
            "description": "The transaction that was started as part of this request. Can only be set in the first response, and only if RunQueryRequest.new_transaction was set in the request. If set, no other fields will be set in this response.",
            "format": "byte",
            "type": "string"
        }
    },
    "type": "object"
},
```

### After

```json
"RunQueryResponse": {
    "description": "The response for Firestore.RunQuery.",
    "id": "RunQueryResponse",
    "items": {
        "properties": {
            "document": {
                "$ref": "Document",
                "description": "A query result. Not set when reporting partial progress."
            },
            "readTime": {
                "description": "The time at which the document was read. This may be monotonically increasing; in this case, the previous documents in the result stream are guaranteed not to have changed between their `read_time` and this one. If the query returns no results, a response with `read_time` and no `document` will be sent, and this represents the time at which the query was run.",
                "format": "google-datetime",
                "type": "string"
            },
            "skippedResults": {
                "description": "The number of results that have been skipped due to an offset between the last response and the current response.",
                "format": "int32",
                "type": "integer"
            },
            "transaction": {
                "description": "The transaction that was started as part of this request. Can only be set in the first response, and only if RunQueryRequest.new_transaction was set in the request. If set, no other fields will be set in this response.",
                "format": "byte",
                "type": "string"
            }
        },
        "type": "object"
    },
    "type": "array"
},
```

**Comment by kevmoo** [comment]
Cool. I've been using this API without problems, so glad I wasn't going crazy. 🙃
