### ISSUE TITLE
clientId.secret cannot be null.. Error thrown null.

### ISSUE THREAD

**Issue by solaristhesun** [google/googleapis.dart#379]
If I create a client id in dart code like this:
`final ClientId clientId = ClientId.serviceAccount(AppConstants.GOOGLE_API_CLIENT_ID);`

It crashes here:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Invalid argument(s): clientId.secret cannot be null.. Error thrown null.
       at .refreshCredentials(.java:101)
       at AutoRefreshingClient.send(AutoRefreshingClient.java:114)
       at ApiRequester._request.simpleRequest(_request.java:220)
       at ApiRequester._request(ApiRequester.java:263)
       at ApiRequester.request(ApiRequester.java:69)
       at AboutResource.get(AboutResource.java:141)
       at GoogleDrive.upload(GoogleDrive.java:46)
```
Because clientId.secret is null, if I use serviceAccount. It works when I use ClientId(AppConstants.GOOGLE_API_CLIENT_ID, ''). Am I doing something wrong here? What is the point of ClientId.serviceAccount, if it cannot be used?

**Comment by kevmoo** [comment]
@solaristhesun – help me understand why I see `java` in the file paths here. Is this a Dart project or a Java project?

Either way, this seems like it's a bug. Can fix.

**Comment by solaristhesun** [comment]
@kevmoo Thanks for the response. It's a dart (flutter) project. The stacktrace is generated by crashlytics. Apparently it assumes that the files are all java.

**Comment by Salakar** [comment]
@solaristhesun any chance could you share with me your Crashlytics exception catching code that you have setup in Dart that is reporting this so I can investigate the `.java` file paths

**Comment by Salakar** [comment]
@solaristhesun any chance could you share with me your Crashlytics exception catching code that you have setup in Dart that is reporting this so I can investigate the `.java` file paths

**Comment by solaristhesun** [comment]
@Salakar 
Flutter packages:
```
- firebase_crashlytics 2.5.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_crashlytics_platform_interface 3.1.13 [collection firebase_core flutter meta plugin_platform_interface]
```

It is integrated like this:
```
void main() async {
  await runZonedGuarded<Future<void>>(
    () async {

      await Firebase.initializeApp();
      // Pass all uncaught errors from the framework to Crashlytics.
      FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
      await FirebaseCrashlytics.instance
          .setCrashlyticsCollectionEnabled(kReleaseMode || AppConstants.CRASHLYTICS_TESTING_ENABLED);

      runApp(
        ...
      );
    },
    (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack),
  );
}
```

**Comment by russellwheatley** [comment]
> @kevmoo Thanks for the response. It's a dart (flutter) project. The stacktrace is generated by crashlytics. Apparently it assumes that the files are all java.

[This issue](https://github.com/FirebaseExtended/flutterfire/issues/6925) has been raised on the FlutterFire repo. I was able to reach out to Firebase Support who were able to reproduce. No ETA on fix, I was asked to keep an eye out on the release notes for updates.

**Comment by jingyu6lu** [comment]
> een raised on the FlutterFire repo. I was able to reach out to Firebase Support who were able to reproduce. No ETA on fix, I was asked to keep

Hello, I am facing the same issues. Did you solve the problem? Thank you.
