### ISSUE TITLE
CloudVideoIntelligenceApi DetailedApiRequestError(status: 403, message: The caller does not have permission)

### ISSUE THREAD

**Issue by cnkygmr** [google/googleapis.dart#401]
My Code:

```
final accountCredentials = ServiceAccountCredentials.fromJson(r'''{
      "type": "service_account",
      "project_id": "...",
      "private_key_id": "...",
      "private_key": "...",
      "client_email": "...",
      "client_id": "...",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "..."
    }''');
    var scopes = [CloudVideoIntelligenceApi.cloudPlatformScope];
    AuthClient client = await clientViaServiceAccount(
        accountCredentials, scopes);
    try {
      final CloudVideoIntelligenceApi cloudVideoIntelligenceApi = CloudVideoIntelligenceApi(
          client);
      GoogleLongrunningOperation googleLongrunningOperation = await cloudVideoIntelligenceApi
          .videos.annotate(
          GoogleCloudVideointelligenceV1AnnotateVideoRequest(
              features: ['EXPLICIT_CONTENT_DETECTION'],
              inputUri: 'gs://...mp4'));
      print(googleLongrunningOperation.response);
    } finally {
      client.close();
    }
```

Why does it keep giving me this error?

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: DetailedApiRequestError(status: 403, message: The caller does not have permission)
flutter: 
#0      _validateResponse (package:_discoveryapis_commons/src/api_requester.dart:298:9)
<asynchronous suspension>
#1      ApiRequester.request (package:_discoveryapis_commons/src/api_requester.dart:72:16)
<asynchronous suspension>
#2      VideosResource.annotate (package:googleapis/videointelligence/v1.dart:486:23)
<asynchronous suspension>
#3      _Messages.lol (package:nabers.dart:352:63)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

**Comment by kevmoo** [comment]
First, I would *never* put a service account in an app you ship to a client. 

Second: there must be something wrong with the credentials. You need to make sure the service account you're using has access to the API you specify.
