### ISSUE TITLE
PlayIntegrityApi  request error 401

### ISSUE THREAD

**Issue by tao111222333444** [google/googleapis.dart#577]
request  code 
```
  PlayIntegrityApi(http.Client()).v1.decodeIntegrityToken(DecodeIntegrityTokenRequest(integrityToken: "integrityTokenfffffffffffff"), "com.example.untitled1",$fields:"sssss").then((value) {
      var ss = value.tokenPayloadExternal?.toJson().toString();
    });
```

error 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DetailedApiRequestError(status: 401, message: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.)
                                                                                                    #0      validateResponse (package:_discoveryapis_commons/src/api_requester.dart:306:9)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      ApiRequester.request (package:_discoveryapis_commons/src/api_requester.dart:72:16)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      V1Resource.decodeIntegrityToken (package:googleapis/playintegrity/v1.dart:100:23)
                                                                                                    <asynchronous suspension>
```

**Comment by kevmoo** [comment]
Sorry. You'll have to lookup how to use these APIs separately. I have no knowledge of the underlying implementation!
